base_url = "https://wiki.kanjon.art"
compile_sass = true
build_search_index = true
generate_feed = false

theme = "anpu"
taxonomies = [
  { name = "categories" },
  { name = "tags" },
]

[markdown]
highlight_code = false

[extra]
anpu_menu_links = [
  { url = "$BASE_URL", name = "home" },
  { url = "https://mt.kanjon.art", name = "kanjon.art" },
  { url = "$BASE_URL/about/", name = "about" },
]
